kind: ConfigMap
metadata:
  name: server
apiVersion: v1
data:
  index.js: |
    const express = require("express");
    const main = require("./handler");
    const app = express();
    const port = 3000;

    app.get("/", (req, res) => {
      const ret = main.main(res);
      console.log(ret);
      res.send(ret);
    });

    app.listen(port, () => {
      console.log(`Example app listening at http://localhost:${port}`);
    });
