apiVersion: v1
kind: Service
metadata:
  labels:
    run: node
  name: node
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    run: node
status:
  loadBalancer: {}
